# Generated by Django 5.0.7 on 2024-07-31 05:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["is_read", "created"]},
        ),
    ]
